minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
allowBuilds:
  '@swc/core': false # via @vitejs/plugin-react-swc
  esbuild: false # via vite
