version: 2
build:
  os: ubuntu-20.04
  tools:
    python: '3.11'
  jobs:
    pre_build:
      - pybabel compile -f -d locale
python:
  install:
    - requirements: docs/requirements.txt
sphinx:
  fail_on_warning: true
