FROM node:22 AS build-stage

RUN corepack enable

WORKDIR /workdir

COPY frontend/package.json frontend/pnpm-lock.yaml frontend/pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts

COPY . .

WORKDIR /workdir/frontend
RUN pnpm exec tsc && pnpm exec vite build

FROM nginxinc/nginx-unprivileged:latest AS production-stage
USER root
ARG client_max_body_size
COPY --from=build-stage --chown=nginx:root /workdir/frontend/dist /usr/share/nginx/html
COPY --chown=nginx:root frontend/default.conf /etc/nginx/conf.d/default.conf
USER nginx
