[tool.black]
line-length = 119
exclude = '/(migrations|node_modules)/'

[tool.isort]
profile = 'black'
line_length = 119
skip = ['migrations']

[tool.pytest.ini_options]
addopts = "--random-order --random-order-bucket=global"
