name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: "**/requirements*.txt"
      - run: pip install -r requirements_dev.txt
      - name: Run checks and tests
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
        # Need to upgrade to Pydantic 2.
        run: pytest -W error -W ignore::DeprecationWarning --cov app
      - env:
          TEST_SETTINGS: True
        # Need to upgrade to Pydantic 2.
        run: pytest -W error -W ignore::DeprecationWarning settings_tests/test_settings.py
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
