name: Translations
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  i18n:
    uses: open-contracting/.github/.github/workflows/i18n-babel.yml@main
    with:
      command: |
        pybabel extract -k '_ i' -o messages.pot app
        pybabel update -N -i messages.pot -d locale
      dependencies: -r requirements.txt
