name: Lint
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/lint.yml@main
    permissions:
      contents: write
    secrets:
      personal-access-token: ${{ secrets.PAT }}
    with:
      # https://fastapi.tiangolo.com/tutorial/request-files/
      # babel and uvicorn are run as commands in a Dockerfile.
      standard-maintenance-scripts-ignore: babel,python-multipart,uvicorn
